car/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = "car"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.LogOut, name="logout"),    
    path("signup/", views.signup, name="signup"),
    path("profile/", login_required(views.OrderListView.as_view()), name="profile"),
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path("car/<int:id>/", views.CarDetailView.as_view(), name="detail"),
    path("car/buy/<int:id>", views.buy, name="buy"),
    path("car/add_comment/<int:car_id>/", views.add_comment, name="add_comment"),
]

django_midterm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("car.urls", namespace="car")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

brand/models.py
from django.db import models

class Brand(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name

car/models.py
from django.db import models
from brand.models import Brand
from django.contrib.auth.models import User

class Car(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to="car/media/uploads/")
    price = models.IntegerField()
    quantity = models.IntegerField()
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
class Comment(models.Model):
    name = models.CharField(max_length=100)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    comment = models.TextField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment[:50]
    
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.time)

car/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms

from .models import Comment

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email',)

class EditProfileForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'comment', )

brand/views.py
from django.shortcuts import render

car/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.views.generic import DetailView, ListView


from .forms import SignupForm, EditProfileForm, CommentForm
from brand.models import Brand
from .models import Car, Order, Comment

def index(request):
    brands = Brand.objects.all()
    if "brand_id" not in request.GET: 
        cars = Car.objects.all()
    else:
        brand_id = request.GET["brand_id"]
        cars = Car.objects.filter(brand__id = brand_id)
    return render(request, "car/index.html", {
        "brands": brands,
        "cars": cars,
    })

def LogOut(request):
    logout(request)
    return redirect(reverse("car:index"))

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, message="Successfully created user")
    else:
        form = SignupForm()
    return render(request, "car/signup.html", {"form": form})

@login_required
def edit_profile(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("car:profile")
    else:
        form = EditProfileForm(instance=request.user)
    return render(request, "car/edit_profile.html", {"form": form})

def buy(request, id):
    if not request.user.is_authenticated:
        return redirect(reverse("car:detail", args=(id,)))
    if request.method == "POST":
        car = get_object_or_404(Car, pk=id)
        if car.quantity > 0:
            car.quantity = F("quantity") - 1
            car.save()

            order = Order(user=request.user, car=car)
            order.save()
        return redirect(reverse("car:detail", args=(id,)))
    
def add_comment(request, car_id):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            car = get_object_or_404(Car, pk=car_id)
            form.instance.car = car
            form.save()
            return redirect(reverse("car:detail", args=(car_id,)))

class UserLoginView(LoginView):
    def get_success_url(self):
        return reverse("car:index")
    
    template_name = "car/login.html"

class CarDetailView(DetailView):
    model = Car
    pk_url_kwarg = "id"
    template_name = "car/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comments = Comment.objects.all()
        context["comment_form"] =  CommentForm()
        context["comments"] = comments
        return context
    

class OrderListView(ListView):
    model = Order
    template_name = "car/profile.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user).order_by("-time")

car/templates/car/detail.html
{% extends 'base.html' %}

{% load static %}
{% block header %}
    <link rel="stylesheet" href="{% static "car/style.css" %}}"/>
{% endblock %}

{% load crispy_forms_tags %}
{% block content %} 
    {% load humanize %}
    <div class="d-flex">
        <div id="banner-text">
            <div class="center">
                <h1>{{ car.name }}</h1>
                <p>{{ car.description }}</p>
                <span><b>Price: </b>${{ car.price | intcomma }}</span><br/>
                <span><b>Quantity: </b>{{ car.quantity }}</span><br/>
                <span><b>Brand: </b>{{ car.brand.name }}</span><br/>
            </div>
        </div>
        <div>
            <img width="400px" src="{{ car.image.url }}" />
        </div>
    </div>
    <div>
        {% if user.is_authenticated %}
            {% if car.quantity > 0 %}
                <form action="{% url "car:buy" car.id %}" method="POST">    
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Buy Now</button>
                </form>
            {% else %}
                <a href="#" class="btn disabled">Out of Stock</a>
            {% endif %}
        {% else %}
            <p>Log In / Sign Up to buy</p>
        {% endif %}
    </div>
    <div>
        <h2>Comments</h2>
        <ul class="list-group">
            {% for comment in comments %}
                <li class="list-group-item">
                    <span><b>{{ comment.name }}</b> - {{ comment.created_at }}</span>
                    <p>{{ comment.comment }}</p>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="mt-2">
        <h2>Add a comment</h2>
        <form action="{% url "car:add_comment" car.id %}" method="POST">
            {% csrf_token %}
            {{ comment_form | crispy }}
            <button class="btn btn-primary" type="submit">Comment</button>
        </form>
    </div>
{% endblock %}

car/templates/car/edit_profile.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}
    {% for message in messages %}
        {{ message }}
    {% endfor %}
    <h1>Edit Profile</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form | crispy }}
        <button class="btn btn-primary" type="submit">Save Changes</button>
    </form>
{% endblock %}

car/templates/car/index.html
{% extends "base.html" %}

{% load static %}

{% block header %}
    <link rel="stylesheet" href="{% static "car/style.css" %}" />
{% endblock %}

{% block content %}
    <div class="d-flex">
        <div id="banner-text">
            <div class="center">
                <h1>Welcome</h1>
                <p>Welcome to our car shop. Here you can buy different cars of various types from our vast collection. Multiple brands have their car ready for you to buy.
                Let's get started.</p>
            </div>
        </div>
        <div>
            <img width="400px" src="{% static "car/assets/car-home.jpg" %}" />
        </div>
    </div>
    <div class="d-flex gap-3">
        {% for brand in brands %}
            <form>
                <input type="hidden" name="brand_id" value="{{ brand.id }}" />
                <button type="submit" class="btn btn-primary">{{ brand.name }}</button>
            </form>
        {% endfor %}
    </div>
    <div class="d-flex flex-wrap gap-3 mt-4">
        {% load humanize %}
        {% for car in cars %}
            <div class="card" style="width: 18rem;">
                <img src="{{ car.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                <h5 class="card-title">{{ car.name }}</h5>
                <p class="card-text">{{ car.description }}</p>
                <span><b>Price: </b>${{ car.price | intcomma }}</span><br/>
                <span><b>Quantity: </b>{{ car.quantity }}</span><br/>
                <span><b>Brand: </b>{{ car.brand.name }}</span><br/>
                <a href="{% url "car:detail" car.id %}" class="btn btn-primary mt-2">Get Details</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

car/templates/car/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}
    {% if user.is_authenticated %}
        Already Logged In
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {{ form | crispy }}
        <button class="btn btn-primary" type="submit">Log In</button>
    </form> 
{% endblock content %}

car/templates/car/profile.html
{% extends 'base.html' %}

{% block content %}
    {% load humanize %}
    <h2>Profile</h2>
    <a href="{% url "car:edit_profile" %}" class="btn btn-primary mb-4">Edit</a>
    <div>
        <table class="table table-striped">
            <tr>
                <td>Username</td>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <td>Name</td>
                <td>{{ user.first_name }} {{ user.last_name }}</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{{ user.email }}</td>
            </tr>
        </table>
    </div>
    <h2>Order History</h2>
    <div>
        {% for order in order_list %}
            <div class="card mx-auto" style="width: 80%;">
                <div class="d-flex">
                    <img src="{{ order.car.image.url }}" class="card-img-top w-25" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ order.car.name }}</h5>
                        <span><b>Brand: </b>{{ order.car.brand }}</span><br/>
                        <span><b>Price: </b>${{ order.car.price | intcomma }}</span><br/>
                        <span><b>Quantity: </b>1</span><br/>
                        <span><b>Ordered At: </b>{{ order.time }}</span><br/> 
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

car/templates/car/signup.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}
    {% for message in messages %}
        {{ message }}
    {% endfor %}
    <form method="POST">
        {% csrf_token %}
        {{ form | crispy }}
        <button class="btn btn-primary" type="submit">Sign Up</button>
    </form>
{% endblock %}

templates/base.html
<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        {% block header %}

        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    Car Shop
                </a>
                <ul class="navbar-nav">
                    {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'car:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'car:signup' %}">Sign Up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'car:login' %}">Log In</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'car:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'car:profile' %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'car:logout' %}">Log Out</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav> 
        <div class="container p-4">
            {% block content %}
                
            {% endblock %}
        </div>
    </body>
</html>